CP-44: Переехать на TypeScript
frontend-park-mail-ru/2020_2_CodeExpress pull request #24
Opened 2020-10-19 18:04 UTC by Sarafa2n

2020-10-19 18:26 UTC, StealthTech requested changes

2020-10-19 18:26 UTC, StealthTech commented on src/components/track-list/track-list.ts
> +export interface track {
Интерфейсы называются с большой буквы. Если это не `State` или `Props`, лучше называть с `I`, типа. `ITrack`

2020-10-19 18:26 UTC, StealthTech commented on src/managers/base-view/base-view.ts
> +export class BaseView extends Component {
`abstract`

2020-10-19 18:26 UTC, StealthTech commented on src/managers/component/component.ts
>  export class Component {
`abstract`

2020-10-19 18:26 UTC, StealthTech commented on src/managers/component/component.ts
> +    constructor(props: IProps, storage: IState) {
Лучше сделать generic-класс. Подробнее: https://www.typescriptlang.org/docs/handbook/generics.html

Тогда можно будет не определять пустой `Props` и `State`

2020-10-19 18:26 UTC, StealthTech commented on src/managers/component/component.ts
> +    setState(obj: any): void {
Здесь вместо `any` можно `Partial<State>` или `Partial<T>`, если сделаешь generic-класс.
Подробнее: https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype

2020-10-19 18:26 UTC, StealthTech commented on src/managers/request/request.ts
> +    static post(url: string, params: RequestBody): Promise<any> {
Потом эти `any` надо постараться убить

2020-10-19 18:26 UTC, StealthTech commented on src/managers/request/request.ts
> +    payload: any,
Почти уверен, что `payload` не `any`, а объект с произвольными ключами и значениями `any`

2020-10-19 18:26 UTC, StealthTech commented on src/managers/router/router.ts
> +interface IRouterState extends IState {
Если сделаешь из базового generic-класс, можно будет не наследоваться от `IState`

2020-10-19 18:26 UTC, StealthTech commented on src/managers/router/router.ts
> +        super(props, {});
Если вторым параметром приходится передавать пустой объект, нужно сделать этот параметр опциональным

2020-10-19 18:26 UTC, StealthTech commented on src/managers/router/router.ts
> +    register(path: string, View: any): this {
Для `View` нет более точного типа, чем `any`?

2020-10-19 18:26 UTC, StealthTech commented on src/managers/validator/validator.ts
> +export interface iValidate {
Выглядит как новый валидатор от компании Apple. Не нужно писать с маленькой буквы здесь

2020-10-19 18:26 UTC, StealthTech commented on src/managers/validator/validator.ts
> +export const userFormValidator = (target: HTMLInputElement, reg: RegExp, helpText: string): iValidate => {
Неясно, что за тип `iValidate`. Лучше уж `IValidationResult`, например

2020-10-19 18:26 UTC, StealthTech commented on src/models/user.ts
> +    attrs: User;
Окей, но в будущем нужно убрать `attrs`, я думаю. TypeScript показывает, что это выглядит странновато

2020-10-19 18:26 UTC, StealthTech commented on src/models/user.ts
> +interface User {
Раз это не `User`, а его `attrs`, лучше назвать интерфейс как-то вроде `IUserAttrs`

2020-10-19 18:26 UTC, StealthTech commented on webpack.config.js
> +                test: /\.ts(x?)$/,
Откуда. Вы. Берете. Этот. `tsx`?!

2020-10-19 18:26 UTC, StealthTech commented on src/components/player/player.ts
> +interface playerState extends IState{
Интерфейсы с большой буквы. Пробел потерялся

2020-10-19 18:47 UTC, Sarafa2n commented on webpack.config.js
> +                test: /\.ts(x?)$/,
в примере был

2020-10-19 18:59 UTC, Sarafa2n commented on src/managers/base-view/base-view.ts
> +export class BaseView extends Component {
поправил

2020-10-19 19:02 UTC, Sarafa2n commented on src/managers/component/component.ts
>  export class Component {
поправил

2020-10-19 19:05 UTC, Sarafa2n commented on src/components/track-list/track-list.ts
> +export interface track {
поправил

2020-10-19 19:06 UTC, Sarafa2n commented on src/managers/request/request.ts
> +    static post(url: string, params: RequestBody): Promise<any> {
ок

2020-10-19 19:06 UTC, Sarafa2n commented on src/managers/request/request.ts
> +    payload: any,
ну как бы да))

2020-10-19 19:07 UTC, Sarafa2n commented on src/managers/router/router.ts
> +        super(props, {});
так и было, просто случайно выпилил

2020-10-19 19:10 UTC, Sarafa2n commented on src/managers/validator/validator.ts
> +export const userFormValidator = (target: HTMLInputElement, reg: RegExp, helpText: string): iValidate => {
согласен, он не нужен, чет я перемудрил

2020-10-19 19:11 UTC, Sarafa2n commented on src/managers/validator/validator.ts
> +export const userFormValidator = (target: HTMLInputElement, reg: RegExp, helpText: string): iValidate => {
поправил

2020-10-19 19:11 UTC, Sarafa2n commented on src/managers/validator/validator.ts
> +export interface iValidate {
убрал

2020-10-19 19:12 UTC, Sarafa2n commented on src/models/user.ts
> +interface User {
поправил

2020-10-19 19:12 UTC, Sarafa2n commented on webpack.config.js
> +                test: /\.ts(x?)$/,
поправил

2020-10-19 21:28 UTC, Sarafa2n commented on src/managers/request/request.ts
> +    payload: any,
поправил

2020-10-20 13:04 UTC, StealthTech submitted a review, later dismissed

2020-10-20 20:10 UTC, StealthTech approved these changes

2020-10-20 20:10 UTC, merged