CP-47: Переверстать текущие страницы под новый макет
frontend-park-mail-ru/2020_2_CodeExpress pull request #26
Opened 2020-10-25 17:26 UTC by Sarafa2n

2020-10-25 17:45 UTC, StealthTech requested changes

2020-10-25 17:45 UTC, StealthTech commented on src/_fonts.scss
> +  font-family: Montserrat-R;
`Montserrat Regular`. Не надо сокращать, зачем?

2020-10-25 17:45 UTC, StealthTech commented on src/components/app/app.scss
> +.button-primary {
Может, кнопка в отдельном компоненте должна жить?

2020-10-25 17:45 UTC, StealthTech commented on src/components/app/app.scss
> +.album-item {
Кажется, что для всего кроме `html`, `body`, `#app`, нужно отдельные компоненты

2020-10-25 17:45 UTC, StealthTech commented on src/components/page/page.scss
> +.sidebars {
Сайдбаров несколько?

2020-10-25 17:45 UTC, StealthTech commented on src/components/player/player.scss
> +.turntable {
Почему файл `player.scss`, а класс `.turntable`?

2020-10-25 17:45 UTC, StealthTech commented on src/components/sidebar/sidebar.scss
> +.left-sidebar {
Почему классы и компоненты не согласуются?

2020-10-25 17:45 UTC, StealthTech commented on src/views/index-view/index.hbs
> +        <div class="article" style="background: linear-gradient(180deg, rgba(0, 0, 0, 7.5e-05) 2.75%, rgba(17, 18, 23, 0.75) 100%), url('../../assets/backgrounds/imagine_dragons.jpg')">
А градиент нельзя под класс спрятать?

2020-10-25 17:45 UTC, StealthTech commented on src/views/index-view/index.hbs
> +        <div class="genre-item">Альтернативный рок</div>
Давай их из контекста прокидывать?

2020-10-25 17:45 UTC, StealthTech commented on src/views/index-view/index.scss
> +.home-page {
Опять с названием что-то не так

2020-10-25 17:45 UTC, StealthTech commented on src/views/profile-view/profile.hbs
> +<!--<div class="profile-page">-->
?!

2020-10-25 17:45 UTC, StealthTech commented on src/views/signup-view/signup.hbs
> +<!--{{{ header }}}-->
?!

2020-10-26 17:37 UTC, Sarafa2n commented on src/_fonts.scss
> +  font-family: Montserrat-R;
поправил

2020-10-26 17:46 UTC, Sarafa2n commented on src/components/app/app.scss
> +.button-primary {
Поправил

2020-10-26 17:57 UTC, Sarafa2n commented on src/components/app/app.scss
> +.album-item {
поправил

2020-10-26 18:05 UTC, Sarafa2n commented on src/components/page/page.scss
> +.sidebars {
поправил

2020-10-26 18:06 UTC, Sarafa2n commented on src/components/player/player.scss
> +.turntable {
поправил

2020-10-26 18:09 UTC, Sarafa2n commented on src/components/sidebar/sidebar.scss
> +.left-sidebar {
поправил

2020-10-26 18:27 UTC, Sarafa2n commented on src/views/index-view/index.hbs
> +        <div class="article" style="background: linear-gradient(180deg, rgba(0, 0, 0, 7.5e-05) 2.75%, rgba(17, 18, 23, 0.75) 100%), url('../../assets/backgrounds/imagine_dragons.jpg')">
поправил

2020-10-26 18:32 UTC, Sarafa2n commented on src/views/index-view/index.hbs
> +        <div class="genre-item">Альтернативный рок</div>
Поправил

2020-10-26 18:33 UTC, Sarafa2n commented on src/views/signup-view/signup.hbs
> +<!--{{{ header }}}-->
случайно

2020-10-26 18:33 UTC, Sarafa2n commented on src/views/profile-view/profile.hbs
> +<!--<div class="profile-page">-->
поправил

2020-10-26 18:34 UTC, Sarafa2n commented on src/views/signup-view/signup.hbs
> +<!--{{{ header }}}-->
поправил

2020-10-26 18:35 UTC, Sarafa2n commented on src/views/index-view/index.scss
> +.home-page {
поправил

2020-10-26 19:20 UTC, StealthTech approved these changes

2020-10-26 19:20 UTC, merged