CP-12: Сверстать страницу артиста
frontend-park-mail-ru/2020_2_CodeExpress pull request #31
Opened 2020-11-02 21:16 UTC by Sarafa2n

2020-11-02 21:38 UTC, StealthTech requested changes

2020-11-02 21:38 UTC, StealthTech commented on src/managers/router/router.ts
> +            const url = (<HTMLLinkElement>target).href.replace(`http://${window.location.hostname}${process.env.DEBUG === 'true' ? `:${process.env.PORT}` : ''}`, '');
Жесть какая. Давай разобьем это на несколько констант

2020-11-02 21:38 UTC, StealthTech commented on src/managers/router/router.ts
> +                const url = parent.href.replace(`http://${window.location.hostname}${process.env.DEBUG === 'true' ? `:${process.env.PORT}` : ''}`, '');
Где-то я уже видел

2020-11-02 21:40 UTC, Sarafa2n commented on src/managers/router/router.ts
> +                const url = parent.href.replace(`http://${window.location.hostname}${process.env.DEBUG === 'true' ? `:${process.env.PORT}` : ''}`, '');
ок

2020-11-03 11:13 UTC, StealthTech approved these changes

2020-11-03 11:13 UTC, merged