Spa cp 16
frontend-park-mail-ru/2020_2_CodeExpress pull request #4
Opened 2020-09-19 14:15 UTC by Sarafa2n

2020-09-19 20:31 UTC, StealthTech requested changes
Направление правильное, круто, что получается правда SPA, и что есть линтер уже на этом этапе! Нужно доработать напильником и 👌

2020-09-19 20:31 UTC, StealthTech commented on src/managers/component/component.js
> +export default class Component {
Аpp не является компонентом?

2020-09-19 20:31 UTC, StealthTech commented on src/managers/router/router.js
> +        this.routers = {};
Наверное, routes?

2020-09-19 20:31 UTC, StealthTech commented on src/managers/router/router.js
> +            View,
Тут не будет путаницы? View и view

2020-09-19 20:31 UTC, StealthTech commented on src/managers/router/router.js
> +            const match = key.match(/([^:]+):?(.+)?/)[2];
Давай выносить регулярки в отдельные константы с понятными названиями

2020-09-19 20:31 UTC, StealthTech commented on src/managers/router/router.js
> +        this.root.addEventListener('click', (event) => {
Не нашел, где происходит removeEventListener

2020-09-19 20:31 UTC, StealthTech commented on src/managers/router/router.js
> +    redirect(path) {
Это наверное не redirect, а go

2020-09-19 20:31 UTC, StealthTech commented on package.json
> +  },
А вот и потерянный express. Так нельзя — каждый PR должен быть на 100% работоспособным

2020-09-19 20:31 UTC, StealthTech commented on src/store/routers.js
> +export default {
Я в итоге отказываюсь от default экспорта в роутах и делаю рез const RouteStore, предлагаю так же. Ну и файл назвать не routers

2020-09-19 20:31 UTC, StealthTech commented on src/managers/router/router.js
> +        if (!view.active) {
Кажется, можно схлопнуть в один ифак

2020-09-19 20:31 UTC, StealthTech commented on src/managers/component/component.js
> +        this.hidden = true;
А почему такая логика с hidden интересная? Компонентом может быть кнопка, например? Если да, то не правильнее будет mount/destroy?

2020-09-19 20:31 UTC, StealthTech commented on package.json
> +    "hooks": {
Супер-респект за husky и pre-commit хук

2020-09-19 20:31 UTC, StealthTech commented on package.json
> +    "eslint": "node_modules/.bin/eslint src/"
Eslint ❤
Но вроде можно просто eslint вызывать, без прямого указания на node_modules

2020-09-19 20:31 UTC, StealthTech commented on src/components/app/app.js
> +        this.routes.start();
Довольно спорное название для функции рендера. Это точно должно быть именно так?

2020-09-19 20:35 UTC, Sarafa2n commented on src/managers/component/component.js
> +export default class Component {
мысль была сделать базовый класс для layout's

2020-09-19 20:35 UTC, Sarafa2n commented on src/managers/router/router.js
> +        this.routers = {};
наверно да

2020-09-19 20:36 UTC, Sarafa2n commented on src/managers/router/router.js
> +            View,
понял, поправлю

2020-09-19 20:37 UTC, Sarafa2n commented on src/managers/router/router.js
> +        this.root.addEventListener('click', (event) => {
ой
а вот этого не сделал

2020-09-20 14:40 UTC, Sarafa2n commented on package.json
> +  },
Выпилил

2020-09-20 14:41 UTC, Sarafa2n commented on package.json
> +    "eslint": "node_modules/.bin/eslint src/"
возможно да, но мне кажется команду из package.json можно не убирать

2020-09-20 22:32 UTC, Sarafa2n commented on src/managers/router/router.js
> +        this.root.addEventListener('click', (event) => {
Вопрос, зачем нам удалять обработчик, если мы его используем многократно

2020-09-25 20:06 UTC, Sarafa2n commented on src/managers/router/router.js
> +        this.routers = {};
поправил

2020-09-26 08:06 UTC, Sarafa2n commented on src/managers/router/router.js
> +            const match = key.match(/([^:]+):?(.+)?/)[2];
поправил

2020-09-26 08:06 UTC, Sarafa2n commented on src/managers/router/router.js
> +    redirect(path) {
поправил

2020-09-26 08:06 UTC, Sarafa2n commented on src/store/routers.js
> +export default {
поправил

2020-09-26 08:22 UTC, Sarafa2n commented on package.json
> +    "eslint": "node_modules/.bin/eslint src/"
поправил

2020-09-26 08:54 UTC, Sarafa2n commented on src/managers/router/router.js
> +            View,
поправил

2020-09-26 09:34 UTC, Sarafa2n commented on src/managers/component/component.js
> +        this.hidden = true;
поправил

2020-09-26 09:35 UTC, Sarafa2n commented on src/managers/router/router.js
> +        if (!view.active) {
нельзя, так как у нас возможно view уже объект класса, и тогда проверка на то, активен ли данный экран не выполнится

2020-09-26 09:45 UTC, Sarafa2n commented on src/managers/router/router.js
> +        if (!view.active) {
а, я понял, поправил

2020-09-29 21:57 UTC, StealthTech requested changes

2020-09-29 21:57 UTC, StealthTech commented on package.json
> +    "eslint": "node_modules/.bin/eslint src/"
Лучше сделать команду `lint`, которая вызывает `eslint ---ignore-path <...>`, где вместо <...> дальше аргументы

2020-09-29 21:57 UTC, StealthTech commented on src/index.html
> +</html>
Пустой строки нету

2020-09-29 21:57 UTC, StealthTech commented on package.json
> +    "express-handlebars": "^5.1.0",
Хм, а зачем? У вас же нет SSR

2020-09-29 21:57 UTC, StealthTech commented on package.json
> -    "debug": "^4.1.1"
Хорошо, что убрал ненужную зависимость

2020-09-29 21:57 UTC, StealthTech commented on package.json
> +    "eslint": "eslint src/"
А почему тут не используем .eslintignore?

2020-09-29 21:57 UTC, StealthTech commented on package.json
> +    "pretest": "eslint --fix --ignore-path .eslintignore src/",
Я бы сделал одну команду `lint`, в которой бы запускал eslint, но без `--fix`. Лучше научиться не допускать ошибок, и искать их по отчету линтера

2020-09-29 21:57 UTC, StealthTech commented on src/assets/css/imorts.css
> +@import "base.css";
Почему файл называется `imorts` :( 
Нужно что-то серьезно делать со внимательностью — очень часто опечатки в названиях

2020-09-29 21:57 UTC, StealthTech commented on src/components/app/app.js
> +// eslint-disable-next-line import/extensions
Выключи пока что тогда уж правило на весь проект — странно выглядит заборчик из исключений

2020-09-29 21:57 UTC, StealthTech commented on src/components/default-slider/default-slider.js
> +    checkBtns() {
Лучше писать полностью. `Buttons`

2020-09-29 21:57 UTC, StealthTech commented on src/components/default-slider/default-slider.js
> +        nextBtn.disabled = this.position <= -(slidesCount - slideToShow) * slideWidth;
Давай правую часть выражения в константу

2020-09-29 21:57 UTC, StealthTech commented on src/components/default-slider/default-slider.js
> +            const slidesLeft = slidesCount - (Math.abs(this.position) + slideToShow * slideWidth) / slideWidth;
Вынеси то что в скобках в константу и напиши пояснение плиз

2020-09-29 21:57 UTC, StealthTech commented on src/components/app/app.js
> +        this.routes = new Route(this.props);
Писал уже ранее. `this.router = new Router`. Почему `routes`, если это не роуты, и `new Route`, если это не роут?

2020-09-29 21:57 UTC, StealthTech commented on src/components/player/player.js
> +    getControlElements() {
jsdoc

2020-09-29 21:57 UTC, StealthTech commented on src/index.js
> +new App({ parent: document.getElementById('app') }).start();
Давай по-нормальному. `const parent`, `const app = new App`, `app.start()`. А то что все в одну кучу

2020-09-29 21:57 UTC, StealthTech commented on src/managers/base-view/base-view.js
> +        this.destroy = true;
Что делает это поле?

2020-09-29 21:57 UTC, StealthTech commented on src/managers/router/router.js
> +export default class Router extends Component {
Предлагаю убрать `default`, чтобы не было соблазна обозвать его как-нибудь непотребно. Вроде `Route`, как было выше

2020-09-29 21:57 UTC, StealthTech commented on src/managers/router/router.js
> +        return this;
Интересное решение с чейнингом

2020-09-29 21:57 UTC, StealthTech commented on src/managers/router/router.js
> +        if (this.state.currentView) {
Если используешь больше одного раза, делай деструктуризацию

2020-09-29 21:57 UTC, StealthTech commented on src/managers/router/router.js
> +        if (event.target.tagName === 'DIV' && event.target.classList.contains('link-btn')) {
А почему только `div`?

2020-09-29 21:57 UTC, StealthTech commented on src/store/reg-templates.js
> +// eslint-disable-next-line import/prefer-default-export
Если приходится так делать, лучше перегрузить основной конфиг и отключить эту настройку

2020-09-29 21:57 UTC, StealthTech commented on src/templates/page.hbs
> +<div class="layout__sidebars">
Не нашел сходу — где этот шаблон используется?

2020-09-29 21:57 UTC, StealthTech commented on src/views/login-view/login-view.js
> +export default class LoginView extends BaseView {
Предлагаю в `BaseView` сделать поле `template` и функцию `renderTemplate`, которая будет внутри себя делать что-то вроде `return Handlebars.templates[this.template]`. Тогда можно будет вынести `template` из `render`

2020-09-29 21:57 UTC, StealthTech commented on src/views/login-view/login-view.js
> +        const header = new HeaderFiller(this.props);
Кажется, что такого рода вещам место вне `render`. Где-то в конструкторе, например

2020-09-29 21:57 UTC, StealthTech commented on src/store/reg-templates.js
> +export const regTemplates = {
Не понял, что это. Нужно пояснение комментарием

2020-09-29 21:57 UTC, StealthTech commented on src/managers/base-view/base-view.js
> +        this.destroy = true;
`destroy` это глагол. Если предполагался признак, то нужно подобрать соответствующее слово. Для булевых значений обычно называют начиная с `is` или `has`. Например, `isApproved` или `hasImages`

2020-09-29 21:57 UTC, StealthTech commented on src/index.html
> +    <link href="/assets/css/imorts.css" rel="stylesheet">
Давай переназовем его в bundle.css

2020-09-29 21:57 UTC, StealthTech commented on src/index.html
> +    <title>Title</title>
Title

2020-09-29 21:57 UTC, StealthTech commented on src/index.html
> +<html lang="en">
`en` — не правда

2020-09-29 21:57 UTC, StealthTech commented on server.js
> +app.use('/scripts', express.static(`${__dirname}/node_modules/handlebars/dist/`));
Ну, тогда бы уж указывал на node_modules. Почему ведет только на `handlebars`, а папка `scripts`?

2020-09-29 21:57 UTC, StealthTech commented on precompiled.sh
> +handlebars src/templates/*.hbs -f src/handlebars.precompiled.js
Почему это `.sh`, а не просто команда в `package.json`?

2020-09-29 21:57 UTC, StealthTech commented on src/components/default-slider/default-slider.js
> +            slider, slides, slidesCount, container, track, slideWidth, movePosition, prevBtn, nextBtn,
Это же не стейт, а просто дочерние элементы. Почему они в `setState`?

2020-09-29 21:57 UTC, StealthTech commented on src/components/default-slider/default-slider.js
> +            item.style.minWidth = `${slideWidth}px`;
Функция, которая называется `get<что-то>` не должна ничего менять

2020-09-29 21:57 UTC, StealthTech commented on src/components/default-slider/default-slider.js
> +    init() {
Учитывая, что здесь возвращается реальный html, это должно называться `render`

2020-09-29 21:57 UTC, StealthTech commented on src/components/default-slider/default-slider.js
> +        prevBtn.disabled = this.position === 0;
Функция, которая начинается на `check` не должна ничего менять — по названию кажется, что она должна вернуть булево значение

2020-09-29 21:57 UTC, StealthTech commented on src/components/page/page.js
> +        this.setState({ sidebar });
Почему два `setState`?

2020-09-29 21:57 UTC, StealthTech commented on src/components/page/page.js
> +        const sideBarParent = parent.querySelector('.layout__sidebars');
Может быть, такие места унести в какие-нибудь геттеры?

2020-09-29 21:57 UTC, StealthTech commented on src/components/player/player.js
> +            audio, lastAudio, playButton, timeLine, progressBar, repeatButton, volumeButton, volumeInput, playerTitle, playerAlbum, playerGroup,
Аналогично — тут всё дочерние элементы, это не стейт

2020-09-29 21:57 UTC, StealthTech commented on src/components/player/player.js
> +        const playerGroup = document.getElementById('player-group-js');
Воу, какой забор — может быть, можно как-нибудь это упростить?

2020-09-29 21:57 UTC, StealthTech commented on src/index.html
> +<script src="/handlebars.precompiled.js"></script>
Давай как-нибудь по-другому его назовем? `templates.js`, может быть?

2020-09-29 21:57 UTC, StealthTech commented on src/managers/router/router.js
> +        this.handlerMouseClick = this.handlerMouseClick.bind(this);
Лучше `handle`

2020-09-29 21:57 UTC, StealthTech commented on src/managers/router/router.js
> +    findArgs(path, key) { // TODO : Доделать маршрутизацию по динамическим урлам.
Извлечение параметров из шаблона роута напрашивается на отдельную функцию вне класса

2020-09-29 21:57 UTC, StealthTech commented on src/views/index-view/index-view.js
> +        page.init();
Я запутался в цикле жизни твоих компонентов — почему init внутри render?

2020-09-29 21:57 UTC, StealthTech commented on src/views/login-view/login-view.js
> +        header.init();
`init` внутри `render`. Кажется, что что-то не так

2020-09-30 05:21 UTC, Sarafa2n commented on src/index.html
> +</html>
аааа, мы все умрем

2020-09-30 05:22 UTC, Sarafa2n commented on package.json
> +    "express-handlebars": "^5.1.0",
а это я тыкался, не вынес, спасибо, вынесу

2020-09-30 05:22 UTC, Sarafa2n commented on package.json
> +    "eslint": "eslint src/"
ой надо бы

2020-09-30 05:23 UTC, Sarafa2n commented on package.json
> +    "pretest": "eslint --fix --ignore-path .eslintignore src/",
ок

2020-09-30 05:23 UTC, Sarafa2n commented on src/assets/css/imorts.css
> +@import "base.css";
Да, надо бы

2020-09-30 05:27 UTC, Sarafa2n commented on src/components/app/app.js
> +        this.routes = new Route(this.props);
ааа, не поправил в app.js

2020-09-30 05:30 UTC, Sarafa2n commented on src/managers/router/router.js
> +        if (event.target.tagName === 'DIV' && event.target.classList.contains('link-btn')) {
а хочу

2020-09-30 05:31 UTC, Sarafa2n commented on src/templates/page.hbs
> +<div class="layout__sidebars">
в page.js

2020-09-30 05:34 UTC, Sarafa2n commented on src/views/login-view/login-view.js
> +export default class LoginView extends BaseView {
хорошая мысль, мне нравится

2020-09-30 05:34 UTC, Sarafa2n commented on src/views/login-view/login-view.js
> +        const header = new HeaderFiller(this.props);
понял

2020-09-30 05:35 UTC, Sarafa2n commented on src/store/reg-templates.js
> +export const regTemplates = {
файл со всеми регулярками

2020-09-30 05:35 UTC, Sarafa2n commented on src/index.html
> +    <link href="/assets/css/imorts.css" rel="stylesheet">
ок

2020-09-30 05:36 UTC, Sarafa2n commented on precompiled.sh
> +handlebars src/templates/*.hbs -f src/handlebars.precompiled.js
а шо так можно было?

2020-09-30 05:37 UTC, Sarafa2n commented on src/components/page/page.js
> +        this.setState({ sidebar });
а я не знаю

2020-09-30 05:39 UTC, Sarafa2n commented on src/managers/router/router.js
> +    findArgs(path, key) { // TODO : Доделать маршрутизацию по динамическим урлам.
понял

2020-09-30 11:46 UTC, Sarafa2n commented on src/index.html
> +</html>
вообще-то есть

2020-09-30 11:47 UTC, Sarafa2n commented on package.json
> +    "express-handlebars": "^5.1.0",
поправил

2020-09-30 11:48 UTC, Sarafa2n commented on package.json
> +    "pretest": "eslint --fix --ignore-path .eslintignore src/",
Ага, сделал

2020-09-30 12:04 UTC, Sarafa2n commented on src/components/app/app.js
> +// eslint-disable-next-line import/extensions
Поправил

2020-09-30 12:06 UTC, Sarafa2n commented on src/components/default-slider/default-slider.js
> +    checkBtns() {
Поправил

2020-09-30 12:07 UTC, Sarafa2n commented on src/components/default-slider/default-slider.js
> +        nextBtn.disabled = this.position <= -(slidesCount - slideToShow) * slideWidth;
Поправил

2020-09-30 12:21 UTC, Sarafa2n commented on src/components/default-slider/default-slider.js
> +            const slidesLeft = slidesCount - (Math.abs(this.position) + slideToShow * slideWidth) / slideWidth;
сделал

2020-09-30 12:22 UTC, Sarafa2n commented on src/components/app/app.js
> +        this.routes = new Route(this.props);
сделал

2020-09-30 12:23 UTC, Sarafa2n commented on src/index.js
> +new App({ parent: document.getElementById('app') }).start();
Поправил

2020-09-30 12:31 UTC, Sarafa2n commented on src/managers/router/router.js
> +export default class Router extends Component {
Поправил

2020-09-30 12:33 UTC, Sarafa2n commented on src/store/reg-templates.js
> +// eslint-disable-next-line import/prefer-default-export
сделал

2020-09-30 12:46 UTC, Sarafa2n commented on src/managers/router/router.js
> +        if (event.target.tagName === 'DIV' && event.target.classList.contains('link-btn')) {
поправил

2020-09-30 13:03 UTC, Sarafa2n commented on precompiled.sh
> +handlebars src/templates/*.hbs -f src/handlebars.precompiled.js
поправил

2020-09-30 13:06 UTC, Sarafa2n commented on server.js
> +app.use('/scripts', express.static(`${__dirname}/node_modules/handlebars/dist/`));
поправил

2020-09-30 13:07 UTC, Sarafa2n commented on src/components/page/page.js
> +        this.setState({ sidebar });
поправил

2020-09-30 13:22 UTC, Sarafa2n commented on src/managers/router/router.js
> +        this.handlerMouseClick = this.handlerMouseClick.bind(this);
поправил

2020-09-30 13:24 UTC, Sarafa2n commented on src/views/index-view/index-view.js
> +        page.init();
я сам запутался

2020-09-30 13:24 UTC, Sarafa2n commented on src/views/login-view/login-view.js
> +        header.init();
соглы

2020-09-30 13:30 UTC, Sarafa2n commented on src/components/default-slider/default-slider.js
> +            item.style.minWidth = `${slideWidth}px`;
поправил

2020-09-30 13:47 UTC, Sarafa2n commented on src/views/index-view/index-view.js
> +        page.init();
поправил

2020-09-30 13:48 UTC, Sarafa2n commented on src/views/login-view/login-view.js
> +        header.init();
поправил

2020-09-30 14:03 UTC, Sarafa2n commented on src/managers/router/router.js
> +    findArgs(path, key) { // TODO : Доделать маршрутизацию по динамическим урлам.
поправил

2020-09-30 14:03 UTC, Sarafa2n commented on src/components/player/player.js
> +            audio, lastAudio, playButton, timeLine, progressBar, repeatButton, volumeButton, volumeInput, playerTitle, playerAlbum, playerGroup,
поправил

2020-09-30 14:04 UTC, Sarafa2n commented on src/components/default-slider/default-slider.js
> +    init() {
поправил

2020-09-30 14:04 UTC, Sarafa2n commented on src/index.html
> +<html lang="en">
поправил

2020-09-30 14:04 UTC, Sarafa2n commented on src/index.html
> +    <title>Title</title>
поправил

2020-09-30 14:05 UTC, Sarafa2n commented on src/index.html
> +<script src="/handlebars.precompiled.js"></script>
поправил

2020-09-30 14:06 UTC, Sarafa2n commented on src/components/default-slider/default-slider.js
> +        prevBtn.disabled = this.position === 0;
поправил

2020-09-30 14:06 UTC, Sarafa2n commented on src/index.html
> +    <link href="/assets/css/imorts.css" rel="stylesheet">
поправил

2020-09-30 14:17 UTC, Sarafa2n commented on src/managers/router/router.js
> +        if (this.state.currentView) {
поправил

2020-09-30 14:23 UTC, Sarafa2n commented on src/components/player/player.js
> +    getControlElements() {
поправил

2020-09-30 14:23 UTC, Sarafa2n commented on package.json
> +    "eslint": "eslint src/"
поправил

2020-09-30 14:24 UTC, Sarafa2n commented on src/assets/css/imorts.css
> +@import "base.css";
поправил

2020-09-30 21:56 UTC, StealthTech approved these changes

2020-09-30 21:59 UTC, merged