CP-66: Адаптивная верстка
frontend-park-mail-ru/2020_2_CodeExpress pull request #42
Opened 2020-11-22 11:08 UTC by Sarafa2n

2020-11-22 18:27 UTC, StealthTech requested changes

2020-11-22 18:27 UTC, StealthTech commented on src/components/header-mobile/header-mobile.ts
> +     * @returns {*|string}
JSDoc не соответствует аннотации TS

2020-11-22 18:27 UTC, StealthTech commented on src/components/header-mobile/header-mobile.ts
> +        const replaceUrl = `https://${window.location.hostname}${port}`;
.href?

2020-11-22 18:27 UTC, StealthTech commented on src/components/header-mobile/header-mobile.scss
> +@media only screen and (max-width: 1000px ) {
Пробелы. Здесь и во всех других таких же местах

2020-11-22 18:27 UTC, StealthTech commented on src/components/mobile_player/mobile_player.ts
> +            album: 'https://musicexpress.sarafa2n.ru:8080/album_posters/726420f0b9599ef1cb70cb66032a47f6',
Почему тут моки? И почему зашиты какие-то абсолютные урлы, хм

2020-11-22 18:27 UTC, StealthTech commented on src/components/mobile_player/mobile_player.ts
> +            (<HTMLElement>target).style.color = loopFlag ? '#ff0052' : 'rgba(207, 234, 242, 0.141559)';
А почему это не через навешивание класса?

2020-11-22 18:27 UTC, StealthTech commented on src/components/sidebar/sidebar.ts
> +            if (item.href.replace(replaceUrl, '') === window.location.pathname) {
Избавляемся от replace-подхода и здесь тоже

2020-11-22 18:27 UTC, StealthTech commented on src/views/album-view/album.hbs
> +<!--        </div>-->
?

2020-11-22 18:28 UTC, Sarafa2n commented on src/components/header-mobile/header-mobile.ts
> +     * @returns {*|string}
ну блин

2020-11-22 19:56 UTC, Sarafa2n commented on src/components/header-mobile/header-mobile.ts
> +        const replaceUrl = `https://${window.location.hostname}${port}`;
поправил

2020-11-22 20:05 UTC, Sarafa2n commented on src/components/header-mobile/header-mobile.scss
> +@media only screen and (max-width: 1000px ) {
поправил

2020-11-22 20:07 UTC, Sarafa2n commented on src/components/sidebar/sidebar.ts
> +            if (item.href.replace(replaceUrl, '') === window.location.pathname) {
поправил

2020-11-22 20:33 UTC, Sarafa2n commented on src/views/album-view/album.hbs
> +<!--        </div>-->
поправил

2020-11-22 20:36 UTC, Sarafa2n commented on src/components/mobile_player/mobile_player.ts
> +            album: 'https://musicexpress.sarafa2n.ru:8080/album_posters/726420f0b9599ef1cb70cb66032a47f6',
сделал TODO

2020-11-22 20:42 UTC, Sarafa2n commented on src/components/mobile_player/mobile_player.ts
> +            (<HTMLElement>target).style.color = loopFlag ? '#ff0052' : 'rgba(207, 234, 242, 0.141559)';
поправил

2020-11-23 11:25 UTC, StealthTech approved these changes

2020-11-23 11:34 UTC, merged