CP-99: Сделать очередь треков
frontend-park-mail-ru/2020_2_CodeExpress pull request #51
Opened 2020-12-08 19:34 UTC by Sarafa2n

2020-12-08 21:47 UTC, StealthTech commented on src/components/app/button.scss
> +.controls_disabled {
Почему не БЭМ?

2020-12-08 21:54 UTC, StealthTech requested changes

2020-12-08 21:54 UTC, StealthTech commented on src/components/mobile-player/mobile-player.ts
> +        this.playButton = [].slice.call(document.querySelectorAll('.play-js'));
о_О зачем такЮ

2020-12-08 21:54 UTC, StealthTech commented on src/components/mobile-player/mobile-player.ts
> +        mobilePlayer.style.top = '-61px';
Зачем отрицательные величины и почему именно -61px?

2020-12-08 21:54 UTC, StealthTech commented on src/components/mobile-player/mobile-player.ts
> +        setTimeout(() => { mobilePlayerWrapper.style.display = 'none'; }, 500);
Зачем это?

2020-12-08 21:54 UTC, StealthTech commented on src/components/mobile-player/mobile-player.ts
> +    hiddenPlayer = () => {
hidden не глагол — что делает функция?

2020-12-08 21:54 UTC, StealthTech commented on src/components/mobile-player/mobile-player.ts
> +    setEventListeners(): void {
Это не сеттер. Тогда setup

2020-12-08 21:54 UTC, StealthTech commented on src/components/player-service/player-service.ts
> +    multiChangeTrack = (event: StorageEvent, repeatButton: HTMLElement, playButton: HTMLElement[], progressBar: HTMLElement[]) => {
Когда много аргументов, лучше их запечатать в объект и задать ему интерфейс. Станет сразу читабельнее

2020-12-08 21:54 UTC, StealthTech commented on src/components/player-service/player-service.ts
> +        if (event.key === 'order' || event.key === 'volume' || event.key === 'index') {
Здесь пригодился бы enum

2020-12-08 21:54 UTC, StealthTech commented on src/components/page/page.ts
> +import { player } from 'components/app/app';
Почему?

2020-12-09 08:48 UTC, Sarafa2n commented on src/components/app/button.scss
> +.controls_disabled {
поправил

2020-12-09 08:51 UTC, Sarafa2n commented on src/components/mobile-player/mobile-player.ts
> +    hiddenPlayer = () => {
исправил на hide

2020-12-09 09:47 UTC, Sarafa2n commented on src/components/mobile-player/mobile-player.ts
> +    setEventListeners(): void {
поправил

2020-12-09 11:44 UTC, Sarafa2n commented on src/components/mobile-player/mobile-player.ts
> +        mobilePlayer.style.top = '-61px';
чтобы спрятать toggle когда открываем мобильный плеер, 61 это его выстота, поэтому -61px

2020-12-09 11:45 UTC, Sarafa2n commented on src/components/mobile-player/mobile-player.ts
> +        setTimeout(() => { mobilePlayerWrapper.style.display = 'none'; }, 500);
это чтобы не было бага при скролле

2020-12-09 19:02 UTC, StealthTech approved these changes

2020-12-09 19:03 UTC, merged